### PR TITLE
UIGraph improved with new features

### PR DESCRIPTION
**Pull request by Oen44**
People been asking me to start creating PR for larger changes so here we are.

UIGraph widget got massive update including:
- Multiple graphs in a single widget
- Showing value of a closest point on a line when widget is hovered
- Better performance due to A LOT of caching
- New Lua functions

otclient_gl_IgQCiYM1xR

Usage example
```lua
local index = self:createGraph() -- create new graph, it will return index of that graph
self:setLineWidth(index, 2) -- set line width for previously created graph
self:setLineColor(index, "#FFC04D") -- line color
self:setTextBackground(index, "#FFFFFF") -- background for the text in info box
self:setInfoText(index, "Price (gold):") -- prefix for the value in info box

for i = 1, 30 do
  self:addValue(index, math.random(0, 10 + i)) -- adding value to the graph
end
```

### CODE REVIEW

**Comment by ericcobblepot** [comment]
how to identify between the bar chart and the line chart ?

image

**Comment by Oen44** [comment]
> how to identify between the bar chart and the line chart ?
> 
> image

Bar chart is not a part of UIGraph, that is just a widget holding widgets acting as bars, no need for a completely new Widget for that.

**Comment by ericcobblepot** [comment]
```
WARNING: [UIGraph::addValue (widget4194)] Graph of index 0 out of bounds.
WARNING: [UIGraph::addValue (widget4204)] Graph of index 0 out of bounds.
WARNING: [UIGraph::addValue (widget4218)] Graph of index 0 out of bounds.
WARNING: [UIGraph::addValue (widget4252)] Graph of index 0 out of bounds.
WARNING: [UIGraph::addValue (widget4264)] Graph of index 0 out of bounds.
```

it breaks vbot 4.8 analyzer

and tooltips does not work as in the gif

**Comment by Oen44** [comment]
> ```
> WARNING: [UIGraph::addValue (widget4194)] Graph of index 0 out of bounds.
> WARNING: [UIGraph::addValue (widget4204)] Graph of index 0 out of bounds.
> WARNING: [UIGraph::addValue (widget4218)] Graph of index 0 out of bounds.
> WARNING: [UIGraph::addValue (widget4252)] Graph of index 0 out of bounds.
> WARNING: [UIGraph::addValue (widget4264)] Graph of index 0 out of bounds.
> ```
> 
> it breaks vbot 4.8 analyzer

Oh my god... Forgot about the stupid bot.

**Comment by Oen44** [comment]
Fixed (I hope)

**Comment by ericcobblepot** [comment]
at least in my test,

I have a crash .-
exception thrown here
`minValue = *minValueIter;`


also many people will have to clear the cache(AppData\Roaming\OTClientV8\otclientv8\bot) or modify analyzer.lua(appdata), as the changes will not be reflected there.

**Comment by Oen44** [comment]
> I have a crash .- exception thrown here `minValue = *minValueIter;`

Ah, that makes sense, fixing.

> also many people will have to clear the cache(AppData\Roaming\OTClientV8\otclientv8\bot) or modify analyzer.lua(appdata), as the changes will not be reflected there.

There is nothing I can do about it.

**Comment by ericcobblepot** [comment]
no crash, but this still appears

```
WARNING: [UIGraph::addValue (widget6487)] Graph of index 0 out of bounds.
WARNING: [UIGraph::addValue (widget6417)] Graph of index 0 out of bounds.
WARNING: [UIGraph::addValue (widget6427)] Graph of index 0 out of bounds.
WARNING: [UIGraph::addValue (widget6441)] Graph of index 4 out of bounds.
WARNING: [UIGraph::addValue (widget6475)] Graph of index 0 out of bounds.
```

**Comment by Oen44** [comment]
> no crash, but this still appears
> 
> ```
> WARNING: [UIGraph::addValue (widget6487)] Graph of index 0 out of bounds.
> WARNING: [UIGraph::addValue (widget6417)] Graph of index 0 out of bounds.
> WARNING: [UIGraph::addValue (widget6427)] Graph of index 0 out of bounds.
> WARNING: [UIGraph::addValue (widget6441)] Graph of index 4 out of bounds.
> WARNING: [UIGraph::addValue (widget6475)] Graph of index 0 out of bounds.
> ```

Ye, forgot to use index, fixed

**Comment by ericcobblepot** [comment]
Shouldn't the graphics be on the same scale? (mathematically speaking)
if
for i = 1, 15 do
for i = 1, 8 do
for i = 1, 30 do
the graph should look like this
image

not like this
image

**Comment by Oen44** [comment]
> Shouldn't the graphics be on the same scale? (mathematically speaking) if for i = 1, 15 do-- yellow for i = 1, 8 do --red for i = 1, 30 do -- blue the graph should look like this image
> 
> not like this image

Then graphs with little values would be  barely visible against graphs with a lot of values.

**Comment by ericcobblepot** [comment]
And how would the graph be interpreted?

If:
for i = 1, 15 do -- gold
for i = 1, 8 do -- panties
for i = 1, 30 do -- points

Example:
I understand that your graph tries to show the value of a certain item over a calendar month, from November 4th to December 4th.
I look at this graph and I say:
On December 3rd, 2024, a certain item had a value of 0 points, 60 panties, or 210 gold.
image

But that interpretation is incorrect, because there are data for panties only until November 12th, and for gold only until November 19th.

**Comment by Oen44** [comment]
> And how would the graph be interpreted?
> 
> If: for i = 1, 15 do -- gold for i = 1, 8 do -- panties for i = 1, 30 do -- points
> 
> Example: I understand that your graph tries to show the value of a certain item over a calendar month, from November 4th to December 4th. I look at this graph and I say: On December 3rd, 2024, a certain item had a value of 0 points, 60 panties, or 210 gold. image
> 
> But that interpretation is incorrect, because there are data for panties only until November 12th, and for gold only until November 19th.

Edited just as you posted. You shouldn't be paying attention to the labels, they are not part of the UIGraph, just separated and hardcoded labels. In my case I would never have different amount of points of each graph, they would share same number (based on selected time period at the top).

**Pull request merged**
